### PR TITLE
Table setup enhancements

### PR DESCRIPTION
**Pull request by catboost3r**
- Added feature to load screenshot from host PC via drag'n'drop. So we can load screenshots from log folder.
- Added show buttons for all search areas. If the screenshot is loaded, it shows the image cropped with such coordinates. Useful for debugging.
- After clicking on `Load template`, `top_left_corner` image is shown. Useful for debugging.
- Refactored a bit `decisionmaker.py`. But didn't change any logic.

anydesk00004

### CODE REVIEW

**Comment by dickreuter** [comment]
This is fantastic. Let me have a look and get back to you. Would be great
to put this in.

Please ensure all the lint tests are passing.

**Comment by rayman1104** [comment]
Fixed lint test!

**Comment by catboost3r** [comment]
Fixed lint test!

**Comment by catboost3r** [comment]
Well, actually logic was a bit changed in the `make_decision` function. So that `preflop_table_analyser` is not called if `preflop_override` is false. The interesting consequence is that fast folding is very very fast now if we make preflop decision based on equity.

**Pull request merged**
